<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c6d3eb05-464f-4a5e-ad3c-75bad12cd4ff</elementGuidId>
    <imagePath></imagePath>
    <name>input_contact_switch</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[4]/span[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#contact-switch</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'contact-switch') and equals(@class,'PrivateSwitchBase-input MuiSwitch-input css-1m9pwf3')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>PrivateSwitchBase-input MuiSwitch-input css-1m9pwf3</value>
        <webElementGuid>3c6acfd0-94cc-4904-bad6-2e7e4a661f81</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>contact-switch</value>
        <webElementGuid>5c81ee9d-250d-44c8-9d42-d075244516bd</webElementGuid>
    </webElementProperties>
</WebElementEntity>