<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>49fa8102-5bf3-4e92-adf6-02ed31846bfd</elementGuidId>
    <imagePath></imagePath>
    <name>input_contact_switch</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[4]/span[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#contact-switch</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'contact-switch') and equals(@class,'PrivateSwitchBase-input MuiSwitch-input css-1m9pwf3')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>PrivateSwitchBase-input MuiSwitch-input css-1m9pwf3</value>
        <webElementGuid>f66ac718-3510-4d5e-ad54-5a4013216a1a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>contact-switch</value>
        <webElementGuid>1a5447c3-31e5-4b5f-b1d1-f4515e469d17</webElementGuid>
    </webElementProperties>
</WebElementEntity>