<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1784c6d7-ec26-4ed4-accd-1cfaab615198</elementGuidId>
    <imagePath></imagePath>
    <name>input_contact_switch</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[4]/span[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#contact-switch</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'contact-switch') and equals(@class,'PrivateSwitchBase-input MuiSwitch-input css-1m9pwf3')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>PrivateSwitchBase-input MuiSwitch-input css-1m9pwf3</value>
        <webElementGuid>71b16104-7008-4db9-afd4-e532668282b3</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>contact-switch</value>
        <webElementGuid>3d7c9572-b32b-40c8-aff9-ab04c81d7c7d</webElementGuid>
    </webElementProperties>
</WebElementEntity>