<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1e6ff2cb-586d-438e-8f8d-b6f191ee3f66</elementGuidId>
    <imagePath></imagePath>
    <name>input_contact_email</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/form[1]/div[1]/div[2]/div[2]/div[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#contact-email</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'contact-email') and equals(@class,'MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1h1jerh')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1h1jerh</value>
        <webElementGuid>87843f0d-32f6-4b27-809e-d94c4d06b05a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>contact-email</value>
        <webElementGuid>ce74488a-668f-41a3-a2aa-87be2e9c4e55</webElementGuid>
    </webElementProperties>
</WebElementEntity>